### ISSUE TITLE
StackOverflowException

### ISSUE THREAD

**Issue by RelatedItemSearchUser** [BlueBasher/WorkItemUpdater#1]
Hi,

I'm using the WorkItemUpdater as part of a TaskGroup for a Build Definition.
I am getting the following error:

2017-06-09T06:27:46.2874550Z ##[section]Starting: WorkItem Updater
2017-06-09T06:27:53.7082768Z Updating WorkItem 29040
2017-06-09T06:27:54.0871103Z 
2017-06-09T06:27:54.0871103Z Process is terminated due to StackOverflowException.
2017-06-09T06:27:55.0158810Z ##[error]Exit code 255 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'E:\agent\_work\_tasks\WorkItemUpdater_7164116a-ed17-48be-9c53-b440b2b1dd2e\1.3.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''E:\agent\_work\_tasks\WorkItemUpdater_7164116a-ed17-48be-9c53-b440b2b1dd2e\1.3.0\task.ps1'''))"'.
2017-06-09T06:27:55.0203460Z ##[section]Finishing: WorkItem Updater

Is there anything I can do to troubleshoot this?

**Comment by BlueBasher** [comment]
Could you run your build with "system.debug" variable set to "true"? That way there will be a lot more logging and hopefully can see something that's causing the StackOverflowException.

**Comment by dipenpatelOEH** [comment]
Hi BlueBasher, I got the stackoverflow error. below is the log

------------------------

2017-07-06T04:44:27.2699100Z Starting task: WorkItem Updater
 
2017-07-06T04:44:27.2709142Z C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; $env:TF_BUILD = 'True' ; Import-Module -Name 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\task.ps1'''))"
 
2017-07-06T04:44:29.1979740Z ##[debug]VstsTaskSdk 0.8.1 commit 
 
2017-07-06T04:44:29.3415746Z ##[debug]Importing function 'Assert-Path'.
 
2017-07-06T04:44:29.3435830Z ##[debug]Importing function 'Find-Files'.
 
2017-07-06T04:44:29.3445872Z ##[debug]Importing function 'Find-Match'.
 
2017-07-06T04:44:29.3465956Z ##[debug]Importing function 'Get-AssemblyReference'.
 
2017-07-06T04:44:29.3475998Z ##[debug]Importing function 'Get-Endpoint'.
 
2017-07-06T04:44:29.3486040Z ##[debug]Importing function 'Get-Input'.
 
2017-07-06T04:44:29.3496082Z ##[debug]Importing function 'Get-LocString'.
 
2017-07-06T04:44:29.3506124Z ##[debug]Importing function 'Get-TaskVariable'.
 
2017-07-06T04:44:29.3516166Z ##[debug]Importing function 'Get-TaskVariableInfo'.
 
2017-07-06T04:44:29.3526208Z ##[debug]Importing function 'Get-TfsClientCredentials'.
 
2017-07-06T04:44:29.3536250Z ##[debug]Importing function 'Get-TfsService'.
 
2017-07-06T04:44:29.3546292Z ##[debug]Importing function 'Get-VssCredentials'.
 
2017-07-06T04:44:29.3566376Z ##[debug]Importing function 'Get-VssHttpClient'.
 
2017-07-06T04:44:29.3576418Z ##[debug]Importing function 'Import-LocStrings'.
 
2017-07-06T04:44:29.3586460Z ##[debug]Importing function 'Invoke-Tool'.
 
2017-07-06T04:44:29.3596502Z ##[debug]Importing function 'New-FindOptions'.
 
2017-07-06T04:44:29.3606544Z ##[debug]Importing function 'New-MatchOptions'.
 
2017-07-06T04:44:29.3616586Z ##[debug]Importing function 'Out-Default'.
 
2017-07-06T04:44:29.3626628Z ##[debug]Importing function 'Select-Match'.
 
2017-07-06T04:44:29.3636670Z ##[debug]Importing function 'Set-TaskVariable'.
 
2017-07-06T04:44:29.3646712Z ##[debug]Importing function 'Trace-EnteringInvocation'.
 
2017-07-06T04:44:29.3656754Z ##[debug]Importing function 'Trace-LeavingInvocation'.
 
2017-07-06T04:44:29.3676838Z ##[debug]Importing function 'Trace-Path'.
 
2017-07-06T04:44:29.3686880Z ##[debug]Importing function 'Write-AddAttachment'.
 
2017-07-06T04:44:29.3696922Z ##[debug]Importing function 'Write-AddBuildTag'.
 
2017-07-06T04:44:29.3706964Z ##[debug]Importing function 'Write-AssociateArtifact'.
 
2017-07-06T04:44:29.3717006Z ##[debug]Importing function 'Write-LogDetail'.
 
2017-07-06T04:44:29.3727048Z ##[debug]Importing function 'Write-SetProgress'.
 
2017-07-06T04:44:29.3737090Z ##[debug]Importing function 'Write-SetResult'.
 
2017-07-06T04:44:29.3757174Z ##[debug]Importing function 'Write-SetSecret'.
 
2017-07-06T04:44:29.3757174Z ##[debug]Importing function 'Write-SetVariable'.
 
2017-07-06T04:44:29.3827468Z ##[debug]Importing function 'Write-TaskDebug'.
 
2017-07-06T04:44:29.3998182Z ##[debug]Importing function 'Write-TaskError'.
 
2017-07-06T04:44:29.4168896Z ##[debug]Importing function 'Write-TaskVerbose'.
 
2017-07-06T04:44:29.4188980Z ##[debug]Importing function 'Write-TaskWarning'.
 
2017-07-06T04:44:29.4199022Z ##[debug]Importing function 'Write-UpdateBuildNumber'.
 
2017-07-06T04:44:29.4209064Z ##[debug]Importing function 'Write-UploadArtifact'.
 
2017-07-06T04:44:29.4219106Z ##[debug]Importing function 'Write-UploadBuildLog'.
 
2017-07-06T04:44:29.4299442Z ##[debug]Entering C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\task.ps1.
 
2017-07-06T04:44:29.4399862Z ##[debug]BUILD_BUILDID: '619'
 
2017-07-06T04:44:29.4429988Z ##[debug]SYSTEM_TEAMPROJECTID: '34147a9c-0c69-4132-aa13-4e2cd697ac95'
 
2017-07-06T04:44:29.4460114Z ##[debug]BUILD_REQUESTEDFOR: 'Dipen Patel'
 
2017-07-06T04:44:29.4620786Z ##[debug]INPUT_WORKITEMTYPE: 'User Story'
 
2017-07-06T04:44:29.4630828Z ##[debug]INPUT_WORKITEMSTATE: 'Active'
 
2017-07-06T04:44:29.4640870Z ##[debug]INPUT_WORKITEMKANBANSTATE: 'In Progress'
 
2017-07-06T04:44:29.4650912Z ##[debug]INPUT_WORKITEMDONE: 'false'
 
2017-07-06T04:44:29.4670996Z ##[debug] Converted to bool: False
 
2017-07-06T04:44:29.4691080Z ##[debug]INPUT_LINKBUILD: 'true'
 
2017-07-06T04:44:29.4701122Z ##[debug] Converted to bool: True
 
2017-07-06T04:44:29.4711164Z ##[debug]INPUT_UPDATEASSIGNEDTO: 'Never'
 
2017-07-06T04:44:29.4741290Z ##[debug]BuildId 619
 
2017-07-06T04:44:29.4741290Z ##[debug]ProjectId 34147a9c-0c69-4132-aa13-4e2cd697ac95
 
2017-07-06T04:44:29.4751332Z ##[debug]requestedFor Dipen Patel
 
2017-07-06T04:44:29.4751332Z ##[debug]workItemType User Story
 
2017-07-06T04:44:29.4761374Z ##[debug]WorkItemState Active
 
2017-07-06T04:44:29.4761374Z ##[debug]WorkItemKanbanState In Progress
 
2017-07-06T04:44:29.4771416Z ##[debug]WorkItemDone False
 
2017-07-06T04:44:29.4781458Z ##[debug]updateAssignedTo Never
 
2017-07-06T04:44:29.4781458Z ##[debug]Converting buildId '619' as int
 
2017-07-06T04:44:29.4791500Z ##[debug]Converting projectId '34147a9c-0c69-4132-aa13-4e2cd697ac95' as GUID
 
2017-07-06T04:44:29.4942130Z ##[debug]Entering Get-VssHttpClient.
 
2017-07-06T04:44:29.5012424Z ##[debug] TypeName: 'Microsoft.TeamFoundation.WorkItemTracking.WebApi.WorkItemTrackingHttpClient'
 
2017-07-06T04:44:29.5052592Z ##[debug]SYSTEM_TEAMFOUNDATIONCOLLECTIONURI: 'http://teamfoundation.environment.nsw.gov.au:8080/tfs/OEH/'
 
2017-07-06T04:44:29.5092760Z ##[debug]Entering Get-VssCredentials.
 
2017-07-06T04:44:29.5102802Z ##[debug] OMDirectory: ''
 
2017-07-06T04:44:29.5173096Z ##[debug]ENDPOINT_URL_SystemVssConnection: 'http://teamfoundation.environment.nsw.gov.au:8080/tfs/OEH/'
 
2017-07-06T04:44:29.5193180Z ##[debug]ENDPOINT_AUTH_SystemVssConnection: '********'
 
2017-07-06T04:44:29.5203222Z ##[debug]ENDPOINT_DATA_SystemVssConnection (empty)
 
2017-07-06T04:44:29.5313684Z ##[debug]Entering Get-OMType.
 
2017-07-06T04:44:29.5333768Z ##[debug] TypeName: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
 
2017-07-06T04:44:29.5343810Z ##[debug] OMKind: 'WebApi'
 
2017-07-06T04:44:29.5353852Z ##[debug] OMDirectory: ''
 
2017-07-06T04:44:29.5373936Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4'
 
2017-07-06T04:44:29.5383978Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
 
2017-07-06T04:44:29.5454272Z ##[debug]The type was not loaded.
 
2017-07-06T04:44:29.5524566Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.OAuth.WebApi.dll'
 
2017-07-06T04:44:29.5534608Z ##[debug]Not found.
 
2017-07-06T04:44:29.5544650Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.OAuth.dll'
 
2017-07-06T04:44:29.5554692Z ##[debug]Not found.
 
2017-07-06T04:44:29.5564734Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.WebApi.dll'
 
2017-07-06T04:44:29.5584818Z ##[debug]Loading assembly: C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.WebApi.dll
 
2017-07-06T04:44:29.6006582Z ##[debug]Resolving 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
 
2017-07-06T04:44:29.6157212Z ##[debug]Resolving 'System.Net.Http.Formatting, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
 
2017-07-06T04:44:29.6358052Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
 
2017-07-06T04:44:29.6388178Z ##[debug]The type was not loaded.
 
2017-07-06T04:44:29.6398220Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.dll'
 
2017-07-06T04:44:29.6408262Z ##[debug]Not found.
 
2017-07-06T04:44:29.6428346Z ##[debug]Leaving Get-OMType.
 
2017-07-06T04:44:29.6458472Z ##[debug]Entering Get-OMType.
 
2017-07-06T04:44:29.6468514Z ##[debug] TypeName: 'Microsoft.VisualStudio.Services.Client.VssOAuthCredential'
 
2017-07-06T04:44:29.6478556Z ##[debug] OMKind: 'WebApi'
 
2017-07-06T04:44:29.6498640Z ##[debug] OMDirectory: ''
 
2017-07-06T04:44:29.6538808Z ##[debug] Require: 'True'
 
2017-07-06T04:44:29.6548850Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4'
 
2017-07-06T04:44:29.6568934Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.Client.VssOAuthCredential'
 
2017-07-06T04:44:29.6578976Z ##[debug]The type was not loaded.
 
2017-07-06T04:44:29.6599060Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.Client.WebApi.dll'
 
2017-07-06T04:44:29.6609102Z ##[debug]Not found.
 
2017-07-06T04:44:29.6629186Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.Client.dll'
 
2017-07-06T04:44:29.6649270Z ##[debug]Loading assembly: C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.Client.dll
 
2017-07-06T04:44:29.7422504Z ##[debug]System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
 
2017-07-06T04:44:29.7492798Z ##[debug]LoaderExceptions[0]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
 
2017-07-06T04:44:29.7492798Z ##[debug]LoaderExceptions[1]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ServiceBus, Version=2.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
 
2017-07-06T04:44:29.7502840Z ##[debug]LoaderExceptions[2]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
 
2017-07-06T04:44:29.7512882Z ##[debug]LoaderExceptions[3]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
 
2017-07-06T04:44:29.7522924Z ##[debug]LoaderExceptions[4]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
 
2017-07-06T04:44:29.7532966Z ##[debug]LoaderExceptions[5]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
 
2017-07-06T04:44:29.7543008Z ##[debug]LoaderExceptions[6]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
 
2017-07-06T04:44:29.7553050Z ##[debug]LoaderExceptions[7]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
 
2017-07-06T04:44:29.7563092Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.Client.VssOAuthCredential'
 
2017-07-06T04:44:29.7573134Z ##[debug]The type was loaded successfully.
 
2017-07-06T04:44:29.7593218Z ##[debug]Leaving Get-OMType.
 
2017-07-06T04:44:29.7673554Z ##[debug]Leaving Get-VssCredentials.
 
2017-07-06T04:44:29.7693638Z ##[debug]Entering Get-OMType.
 
2017-07-06T04:44:29.7693638Z ##[debug] TypeName: 'Microsoft.TeamFoundation.WorkItemTracking.WebApi.WorkItemTrackingHttpClient'
 
2017-07-06T04:44:29.7703680Z ##[debug] OMKind: 'WebApi'
 
2017-07-06T04:44:29.7713722Z ##[debug] OMDirectory: ''
 
2017-07-06T04:44:29.7723764Z ##[debug] Require: 'True'
 
2017-07-06T04:44:29.7733806Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4'
 
2017-07-06T04:44:29.7743848Z ##[debug]Testing whether type can be loaded: 'Microsoft.TeamFoundation.WorkItemTracking.WebApi.WorkItemTrackingHttpClient'
 
2017-07-06T04:44:29.7804100Z ##[debug]The type was not loaded.
 
2017-07-06T04:44:29.7814142Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.TeamFoundation.WorkItemTracking.WebApi.WebApi.dll'
 
2017-07-06T04:44:29.7824184Z ##[debug]Not found.
 
2017-07-06T04:44:29.7834226Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.TeamFoundation.WorkItemTracking.WebApi.dll'
 
2017-07-06T04:44:29.7844268Z ##[debug]Loading assembly: C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.TeamFoundation.WorkItemTracking.WebApi.dll
 
2017-07-06T04:44:29.7894478Z ##[debug]Testing whether type can be loaded: 'Microsoft.TeamFoundation.WorkItemTracking.WebApi.WorkItemTrackingHttpClient'
 
2017-07-06T04:44:29.7914562Z ##[debug]The type was loaded successfully.
 
2017-07-06T04:44:29.7924604Z ##[debug]Leaving Get-OMType.
 
2017-07-06T04:44:29.7934646Z ##[debug]Constructing HTTP client.
 
2017-07-06T04:44:29.8266032Z ##[debug]Leaving Get-VssHttpClient.
 
2017-07-06T04:44:29.8286116Z ##[debug]Entering Get-VssHttpClient.
 
2017-07-06T04:44:29.8296158Z ##[debug] TypeName: 'Microsoft.TeamFoundation.Build.WebApi.BuildHttpClient'
 
2017-07-06T04:44:29.8306200Z ##[debug]SYSTEM_TEAMFOUNDATIONCOLLECTIONURI: 'http://teamfoundation.environment.nsw.gov.au:8080/tfs/OEH/'
 
2017-07-06T04:44:29.8326284Z ##[debug]Entering Get-VssCredentials.
 
2017-07-06T04:44:29.8326284Z ##[debug] OMDirectory: ''
 
2017-07-06T04:44:29.8346368Z ##[debug]ENDPOINT_URL_SystemVssConnection: 'http://teamfoundation.environment.nsw.gov.au:8080/tfs/OEH/'
 
2017-07-06T04:44:29.8356410Z ##[debug]ENDPOINT_AUTH_SystemVssConnection: '********'
 
2017-07-06T04:44:29.8366452Z ##[debug]ENDPOINT_DATA_SystemVssConnection (empty)
 
2017-07-06T04:44:29.8376494Z ##[debug]Entering Get-OMType.
 
2017-07-06T04:44:29.8386536Z ##[debug] TypeName: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
 
2017-07-06T04:44:29.8396578Z ##[debug] OMKind: 'WebApi'
 
2017-07-06T04:44:29.8406620Z ##[debug] OMDirectory: ''
 
2017-07-06T04:44:29.8416662Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4'
 
2017-07-06T04:44:29.8426704Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
 
2017-07-06T04:44:29.8446788Z ##[debug]The type was not loaded.
 
2017-07-06T04:44:29.8456830Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.OAuth.WebApi.dll'
 
2017-07-06T04:44:29.8466872Z ##[debug]Not found.
 
2017-07-06T04:44:29.8486956Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.OAuth.dll'
 
2017-07-06T04:44:29.8496998Z ##[debug]Not found.
 
2017-07-06T04:44:29.8507040Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.WebApi.dll'
 
2017-07-06T04:44:29.8517082Z ##[debug]Loading assembly: C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.WebApi.dll
 
2017-07-06T04:44:29.8537166Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
 
2017-07-06T04:44:29.8547208Z ##[debug]The type was not loaded.
 
2017-07-06T04:44:29.8557250Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.VisualStudio.Services.dll'
 
2017-07-06T04:44:29.8577334Z ##[debug]Not found.
 
2017-07-06T04:44:29.8587376Z ##[debug]Leaving Get-OMType.
 
2017-07-06T04:44:29.8597418Z ##[debug]Entering Get-OMType.
 
2017-07-06T04:44:29.8607460Z ##[debug] TypeName: 'Microsoft.VisualStudio.Services.Client.VssOAuthCredential'
 
2017-07-06T04:44:29.8617502Z ##[debug] OMKind: 'WebApi'
 
2017-07-06T04:44:29.8627544Z ##[debug] OMDirectory: ''
 
2017-07-06T04:44:29.8647628Z ##[debug] Require: 'True'
 
2017-07-06T04:44:29.8657670Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4'
 
2017-07-06T04:44:29.8667712Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.Client.VssOAuthCredential'
 
2017-07-06T04:44:29.8677754Z ##[debug]The type was loaded successfully.
 
2017-07-06T04:44:29.8687796Z ##[debug]Leaving Get-OMType.
 
2017-07-06T04:44:29.8697838Z ##[debug]Leaving Get-VssCredentials.
 
2017-07-06T04:44:29.8707880Z ##[debug]Entering Get-OMType.
 
2017-07-06T04:44:29.8717922Z ##[debug] TypeName: 'Microsoft.TeamFoundation.Build.WebApi.BuildHttpClient'
 
2017-07-06T04:44:29.8727964Z ##[debug] OMKind: 'WebApi'
 
2017-07-06T04:44:29.8738006Z ##[debug] OMDirectory: ''
 
2017-07-06T04:44:29.8748048Z ##[debug] Require: 'True'
 
2017-07-06T04:44:29.8758090Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4'
 
2017-07-06T04:44:29.8768132Z ##[debug]Testing whether type can be loaded: 'Microsoft.TeamFoundation.Build.WebApi.BuildHttpClient'
 
2017-07-06T04:44:29.8778174Z ##[debug]The type was not loaded.
 
2017-07-06T04:44:29.8788216Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.TeamFoundation.Build.WebApi.WebApi.dll'
 
2017-07-06T04:44:29.8798258Z ##[debug]Not found.
 
2017-07-06T04:44:29.8808300Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.TeamFoundation.Build.WebApi.dll'
 
2017-07-06T04:44:29.8818342Z ##[debug]Loading assembly: C:\PVV_agent\tasks\WorkItemUpdater\1.3.4\Microsoft.TeamFoundation.Build.WebApi.dll
 
2017-07-06T04:44:29.8888636Z ##[debug]Testing whether type can be loaded: 'Microsoft.TeamFoundation.Build.WebApi.BuildHttpClient'
 
2017-07-06T04:44:29.8898678Z ##[debug]The type was loaded successfully.
 
2017-07-06T04:44:29.8908720Z ##[debug]Leaving Get-OMType.
 
2017-07-06T04:44:29.8918762Z ##[debug]Constructing HTTP client.
 
2017-07-06T04:44:29.8938846Z ##[debug]Leaving Get-VssHttpClient.
 
2017-07-06T04:44:29.8958930Z ##[debug]GetBuildWorkItemsRefsAsync 34147a9c-0c69-4132-aa13-4e2cd697ac95 619
 
2017-07-06T04:44:30.2885352Z ##[debug]Loop workItemsRefs
 
2017-07-06T04:44:30.2905436Z ##[debug]Microsoft.VisualStudio.Services.WebApi.ResourceRef Microsoft.VisualStudio.Services.WebApi.ResourceRef
 
2017-07-06T04:44:30.3126360Z ##[debug]Found WorkItemRef: 2009
 
2017-07-06T04:44:30.7605092Z ##[debug]Found WorkItem: 2009
 
2017-07-06T04:44:30.7615134Z ##[debug]Skipped Task WorkItem: 2009
 
2017-07-06T04:44:30.7625176Z ##[debug]Found WorkItemRef: 1896
 
2017-07-06T04:44:30.8538998Z ##[debug]Found WorkItem: 1896
 
2017-07-06T04:44:30.8538998Z Updating WorkItem 1896
 
2017-07-06T04:44:30.8579166Z ##[debug]Found KanbanColumn: WEF_13B56BE23846402A897F92E3C089F35C_Kanban.Column WEF_D0CEBEC070DA4D549967B81DF159CD86_Kanban.Column WEF_C54A9D74724A40879251DD62A6A5A4C4_Kanban.Column WEF_B9CFDA2C487E4819BFB2C149BBE69E55_Kanban.Column WEF_90C4902BB70E426796AB02912F3948E7_Kanban.Column WEF_FBFDA0C4023D47D9927933703E6E21DC_Kanban.Column WEF_CE3336052F9147E3A2A08F3D8493B002_Kanban.Column
 
2017-07-06T04:44:30.8709712Z ##[debug]Patch: /fields/System.State Active
 
2017-07-06T04:44:30.8739838Z ##[debug]Patch: /fields/WEF_13B56BE23846402A897F92E3C089F35C_Kanban.Column WEF_D0CEBEC070DA4D549967B81DF159CD86_Kanban.Column WEF_C54A9D74724A40879251DD62A6A5A4C4_Kanban.Column WEF_B9CFDA2C487E4819BFB2C149BBE69E55_Kanban.Column WEF_90C4902BB70E426796AB02912F3948E7_Kanban.Column WEF_FBFDA0C4023D47D9927933703E6E21DC_Kanban.Column WEF_CE3336052F9147E3A2A08F3D8493B002_Kanban.Column In Progress
 
2017-07-06T04:44:30.8749880Z ##[debug]Patch: /fields/WEF_13B56BE23846402A897F92E3C089F35C_Kanban.Column WEF_D0CEBEC070DA4D549967B81DF159CD86_Kanban.Column WEF_C54A9D74724A40879251DD62A6A5A4C4_Kanban.Column WEF_B9CFDA2C487E4819BFB2C149BBE69E55_Kanban.Column WEF_90C4902BB70E426796AB02912F3948E7_Kanban.Column WEF_FBFDA0C4023D47D9927933703E6E21DC_Kanban.Column WEF_CE3336052F9147E3A2A08F3D8493B002_Kanban.Column.Done False
 
2017-07-06T04:44:30.8840258Z Linking Build 619 to WorkItem 1896
 
2017-07-06T04:44:30.8870384Z ##[debug]Patch: /relations/- vstfs:///Build/Build/619
 
2017-07-06T04:44:31.1109750Z Process is terminated due to StackOverflowException.
 
2017-07-06T04:44:32.1924984Z ##[error]Process completed with exit code 255.
 
2017-07-06T04:44:32.2105740Z Finishing task: WorkItemUpdater
 
2017-07-06T04:44:32.2125824Z ##[error]System.Exception: Task WorkItemUpdater failed. This caused the job to fail. Look at the logs for the task for more details.
 
2017-07-06T04:44:32.2125824Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.Run(IJobContext jobContext, IJobRequest job, IJobExtension jobExtension, CancellationTokenSource tokenSource)

**Comment by BlueBasher** [comment]
@dipenpatelOEH Thanks for the details log! It looks like there's something wrong when a WorkItemType is linked to multiple backlogs.
I will have a look later today when I'm back at home.

**Comment by BlueBasher** [comment]
This issue is fixed in release 1.3.6.
The WorkItemUpdater now has support to update WorkItem Types that are maintained on multiple Kanban boards.

**Comment by dipenpatelOEH** [comment]
Hi,

I am still having the same issue, Kanban hierarchy attached for your reference. It fails regardless what options I choose in the task, i.e. try with and without specifying Kanban Board Column Name, Check/Uncheck “Done” etc


[cid:image002.jpg@01D2F96E.E0BFA320]


1.  2017-07-10T01:17:12.8411165Z C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; $env:TF_BUILD = 'True' ; Import-Module -Name 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\task.ps1'''))"
2.  2017-07-10T01:17:17.1585482Z ##[debug]VstsTaskSdk 0.8.1 commit
3.  2017-07-10T01:17:17.3155639Z ##[debug]Importing function 'Assert-Path'.
4.  2017-07-10T01:17:17.3165640Z ##[debug]Importing function 'Find-Files'.
5.  2017-07-10T01:17:17.3185642Z ##[debug]Importing function 'Find-Match'.
6.  2017-07-10T01:17:17.3195643Z ##[debug]Importing function 'Get-AssemblyReference'.
7.  2017-07-10T01:17:17.3205644Z ##[debug]Importing function 'Get-Endpoint'.
8.  2017-07-10T01:17:17.3215645Z ##[debug]Importing function 'Get-Input'.
9.  2017-07-10T01:17:17.3225646Z ##[debug]Importing function 'Get-LocString'.
10. 2017-07-10T01:17:17.3255649Z ##[debug]Importing function 'Get-TaskVariable'.
11. 2017-07-10T01:17:17.3275651Z ##[debug]Importing function 'Get-TaskVariableInfo'.
12. 2017-07-10T01:17:17.3285652Z ##[debug]Importing function 'Get-TfsClientCredentials'.
13. 2017-07-10T01:17:17.3295653Z ##[debug]Importing function 'Get-TfsService'.
14. 2017-07-10T01:17:17.3305654Z ##[debug]Importing function 'Get-VssCredentials'.
15. 2017-07-10T01:17:17.3315655Z ##[debug]Importing function 'Get-VssHttpClient'.
16. 2017-07-10T01:17:17.3325656Z ##[debug]Importing function 'Import-LocStrings'.
17. 2017-07-10T01:17:17.3335657Z ##[debug]Importing function 'Invoke-Tool'.
18. 2017-07-10T01:17:17.3345658Z ##[debug]Importing function 'New-FindOptions'.
19. 2017-07-10T01:17:17.3355659Z ##[debug]Importing function 'New-MatchOptions'.
20. 2017-07-10T01:17:17.3375661Z ##[debug]Importing function 'Out-Default'.
21. 2017-07-10T01:17:17.3385662Z ##[debug]Importing function 'Select-Match'.
22. 2017-07-10T01:17:17.3385662Z ##[debug]Importing function 'Set-TaskVariable'.
23. 2017-07-10T01:17:17.3405664Z ##[debug]Importing function 'Trace-EnteringInvocation'.
24. 2017-07-10T01:17:17.3415665Z ##[debug]Importing function 'Trace-LeavingInvocation'.
25. 2017-07-10T01:17:17.3425666Z ##[debug]Importing function 'Trace-Path'.
26. 2017-07-10T01:17:17.3435667Z ##[debug]Importing function 'Write-AddAttachment'.
27. 2017-07-10T01:17:17.3445668Z ##[debug]Importing function 'Write-AddBuildTag'.
28. 2017-07-10T01:17:17.3455669Z ##[debug]Importing function 'Write-AssociateArtifact'.
29. 2017-07-10T01:17:17.3465670Z ##[debug]Importing function 'Write-LogDetail'.
30. 2017-07-10T01:17:17.3475671Z ##[debug]Importing function 'Write-SetProgress'.
31. 2017-07-10T01:17:17.3485672Z ##[debug]Importing function 'Write-SetResult'.
32. 2017-07-10T01:17:17.3495673Z ##[debug]Importing function 'Write-SetSecret'.
33. 2017-07-10T01:17:17.3505674Z ##[debug]Importing function 'Write-SetVariable'.
34. 2017-07-10T01:17:17.3565680Z ##[debug]Importing function 'Write-TaskDebug'.
35. 2017-07-10T01:17:17.3585682Z ##[debug]Importing function 'Write-TaskError'.
36. 2017-07-10T01:17:17.3595683Z ##[debug]Importing function 'Write-TaskVerbose'.
37. 2017-07-10T01:17:17.3605684Z ##[debug]Importing function 'Write-TaskWarning'.
38. 2017-07-10T01:17:17.3815705Z ##[debug]Importing function 'Write-UpdateBuildNumber'.
39. 2017-07-10T01:17:17.3835707Z ##[debug]Importing function 'Write-UploadArtifact'.
40. 2017-07-10T01:17:17.3845708Z ##[debug]Importing function 'Write-UploadBuildLog'.
41. 2017-07-10T01:17:17.3935717Z ##[debug]Entering C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\task.ps1.
42. 2017-07-10T01:17:17.4155739Z ##[debug]BUILD_BUILDID: '624'
43. 2017-07-10T01:17:17.4205744Z ##[debug]SYSTEM_TEAMPROJECTID: '34147a9c-0c69-4132-aa13-4e2cd697ac95'
44. 2017-07-10T01:17:17.4245748Z ##[debug]BUILD_REQUESTEDFOR: 'Dipen Patel'
45. 2017-07-10T01:17:17.4435767Z ##[debug]INPUT_WORKITEMTYPE: 'User Story'
46. 2017-07-10T01:17:17.4465770Z ##[debug]INPUT_WORKITEMSTATE: 'Active'
47. 2017-07-10T01:17:17.4485772Z ##[debug]INPUT_WORKITEMKANBANSTATE (empty)
48. 2017-07-10T01:17:17.4525776Z ##[debug]INPUT_WORKITEMDONE: 'false'
49. 2017-07-10T01:17:17.4555779Z ##[debug] Converted to bool: False
50. 2017-07-10T01:17:17.4585782Z ##[debug]INPUT_LINKBUILD: 'false'
51. 2017-07-10T01:17:17.4595783Z ##[debug] Converted to bool: False
52. 2017-07-10T01:17:17.4615785Z ##[debug]INPUT_UPDATEASSIGNEDTO: 'Never'
53. 2017-07-10T01:17:17.4645788Z ##[debug]BuildId 624
54. 2017-07-10T01:17:17.4655789Z ##[debug]ProjectId 34147a9c-0c69-4132-aa13-4e2cd697ac95
55. 2017-07-10T01:17:17.4665790Z ##[debug]requestedFor Dipen Patel
56. 2017-07-10T01:17:17.4675791Z ##[debug]workItemType User Story
57. 2017-07-10T01:17:17.4675791Z ##[debug]WorkItemState Active
58. 2017-07-10T01:17:17.4685792Z ##[debug]WorkItemKanbanState
59. 2017-07-10T01:17:17.4695793Z ##[debug]WorkItemDone False
60. 2017-07-10T01:17:17.4705794Z ##[debug]updateAssignedTo Never
61. 2017-07-10T01:17:17.4705794Z ##[debug]Converting buildId '624' as int
62. 2017-07-10T01:17:17.4715795Z ##[debug]Converting projectId '34147a9c-0c69-4132-aa13-4e2cd697ac95' as GUID
63. 2017-07-10T01:17:17.4885812Z ##[debug]Entering Get-VssHttpClient.
64. 2017-07-10T01:17:17.4955819Z ##[debug] TypeName: 'Microsoft.TeamFoundation.WorkItemTracking.WebApi.WorkItemTrackingHttpClient'
65. 2017-07-10T01:17:17.4985822Z ##[debug]SYSTEM_TEAMFOUNDATIONCOLLECTIONURI: 'http://teamfoundation.environment.nsw.gov.au:8080/tfs/OEH/'
66. 2017-07-10T01:17:17.5015825Z ##[debug]Entering Get-VssCredentials.
67. 2017-07-10T01:17:17.5025826Z ##[debug] OMDirectory: ''
68. 2017-07-10T01:17:17.5095833Z ##[debug]ENDPOINT_URL_SystemVssConnection: 'http://teamfoundation.environment.nsw.gov.au:8080/tfs/OEH/'
69. 2017-07-10T01:17:17.5115835Z ##[debug]ENDPOINT_AUTH_SystemVssConnection: '********'
70. 2017-07-10T01:17:17.5125836Z ##[debug]ENDPOINT_DATA_SystemVssConnection (empty)
71. 2017-07-10T01:17:17.5225846Z ##[debug]Entering Get-OMType.
72. 2017-07-10T01:17:17.5235847Z ##[debug] TypeName: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
73. 2017-07-10T01:17:17.5245848Z ##[debug] OMKind: 'WebApi'
74. 2017-07-10T01:17:17.5255849Z ##[debug] OMDirectory: ''
75. 2017-07-10T01:17:17.5265850Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6'
76. 2017-07-10T01:17:17.5275851Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
77. 2017-07-10T01:17:17.5355859Z ##[debug]The type was not loaded.
78. 2017-07-10T01:17:17.5425866Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.OAuth.WebApi.dll'
79. 2017-07-10T01:17:17.5535877Z ##[debug]Not found.
80. 2017-07-10T01:17:17.5545878Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.OAuth.dll'
81. 2017-07-10T01:17:17.5555879Z ##[debug]Not found.
82. 2017-07-10T01:17:17.5565880Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.WebApi.dll'
83. 2017-07-10T01:17:17.5575881Z ##[debug]Loading assembly: C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.WebApi.dll
84. 2017-07-10T01:17:17.6005924Z ##[debug]Resolving 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
85. 2017-07-10T01:17:17.7046028Z ##[debug]Resolving 'System.Net.Http.Formatting, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
86. 2017-07-10T01:17:17.7286052Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
87. 2017-07-10T01:17:17.7316055Z ##[debug]The type was not loaded.
88. 2017-07-10T01:17:17.7326056Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.dll'
89. 2017-07-10T01:17:17.7336057Z ##[debug]Not found.
90. 2017-07-10T01:17:17.7346058Z ##[debug]Leaving Get-OMType.
91. 2017-07-10T01:17:17.7366060Z ##[debug]Entering Get-OMType.
92. 2017-07-10T01:17:17.7376061Z ##[debug] TypeName: 'Microsoft.VisualStudio.Services.Client.VssOAuthCredential'
93. 2017-07-10T01:17:17.7386062Z ##[debug] OMKind: 'WebApi'
94. 2017-07-10T01:17:17.7396063Z ##[debug] OMDirectory: ''
95. 2017-07-10T01:17:17.7566080Z ##[debug] Require: 'True'
96. 2017-07-10T01:17:17.7576081Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6'
97. 2017-07-10T01:17:17.7586082Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.Client.VssOAuthCredential'
98. 2017-07-10T01:17:17.7606084Z ##[debug]The type was not loaded.
99. 2017-07-10T01:17:17.7616085Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.Client.WebApi.dll'
100.             2017-07-10T01:17:17.7626086Z ##[debug]Not found.
101.             2017-07-10T01:17:17.7636087Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.Client.dll'
102.             2017-07-10T01:17:17.7646088Z ##[debug]Loading assembly: C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.Client.dll
103.             2017-07-10T01:17:17.8406164Z ##[debug]System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
104.             2017-07-10T01:17:17.8486172Z ##[debug]LoaderExceptions[0]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
105.             2017-07-10T01:17:17.8496173Z ##[debug]LoaderExceptions[1]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ServiceBus, Version=2.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
106.             2017-07-10T01:17:17.8496173Z ##[debug]LoaderExceptions[2]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
107.             2017-07-10T01:17:17.8516175Z ##[debug]LoaderExceptions[3]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
108.             2017-07-10T01:17:17.8526176Z ##[debug]LoaderExceptions[4]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
109.             2017-07-10T01:17:17.8536177Z ##[debug]LoaderExceptions[5]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
110.             2017-07-10T01:17:17.8546178Z ##[debug]LoaderExceptions[6]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
111.             2017-07-10T01:17:17.8556179Z ##[debug]LoaderExceptions[7]: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
112.             2017-07-10T01:17:17.8566180Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.Client.VssOAuthCredential'
113.             2017-07-10T01:17:17.8576181Z ##[debug]The type was loaded successfully.
114.             2017-07-10T01:17:17.8596183Z ##[debug]Leaving Get-OMType.
115.             2017-07-10T01:17:17.8686192Z ##[debug]Leaving Get-VssCredentials.
116.             2017-07-10T01:17:17.8706194Z ##[debug]Entering Get-OMType.
117.             2017-07-10T01:17:17.8706194Z ##[debug] TypeName: 'Microsoft.TeamFoundation.WorkItemTracking.WebApi.WorkItemTrackingHttpClient'
118.             2017-07-10T01:17:17.8716195Z ##[debug] OMKind: 'WebApi'
119.             2017-07-10T01:17:17.8726196Z ##[debug] OMDirectory: ''
120.             2017-07-10T01:17:17.8736197Z ##[debug] Require: 'True'
121.             2017-07-10T01:17:17.8746198Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6'
122.             2017-07-10T01:17:17.8756199Z ##[debug]Testing whether type can be loaded: 'Microsoft.TeamFoundation.WorkItemTracking.WebApi.WorkItemTrackingHttpClient'
123.             2017-07-10T01:17:17.8826206Z ##[debug]The type was not loaded.
124.             2017-07-10T01:17:17.8826206Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.TeamFoundation.WorkItemTracking.WebApi.WebApi.dll'
125.             2017-07-10T01:17:17.8836207Z ##[debug]Not found.
126.             2017-07-10T01:17:17.8856209Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.TeamFoundation.WorkItemTracking.WebApi.dll'
127.             2017-07-10T01:17:17.8866210Z ##[debug]Loading assembly: C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.TeamFoundation.WorkItemTracking.WebApi.dll
128.             2017-07-10T01:17:17.8916215Z ##[debug]Testing whether type can be loaded: 'Microsoft.TeamFoundation.WorkItemTracking.WebApi.WorkItemTrackingHttpClient'
129.             2017-07-10T01:17:17.8926216Z ##[debug]The type was loaded successfully.
130.             2017-07-10T01:17:17.8936217Z ##[debug]Leaving Get-OMType.
131.             2017-07-10T01:17:17.8946218Z ##[debug]Constructing HTTP client.
132.             2017-07-10T01:17:17.9286252Z ##[debug]Leaving Get-VssHttpClient.
133.             2017-07-10T01:17:17.9306254Z ##[debug]Entering Get-VssHttpClient.
134.             2017-07-10T01:17:17.9316255Z ##[debug] TypeName: 'Microsoft.TeamFoundation.Build.WebApi.BuildHttpClient'
135.             2017-07-10T01:17:17.9326256Z ##[debug]SYSTEM_TEAMFOUNDATIONCOLLECTIONURI: 'http://teamfoundation.environment.nsw.gov.au:8080/tfs/OEH/'
136.             2017-07-10T01:17:17.9346258Z ##[debug]Entering Get-VssCredentials.
137.             2017-07-10T01:17:17.9356259Z ##[debug] OMDirectory: ''
138.             2017-07-10T01:17:17.9366260Z ##[debug]ENDPOINT_URL_SystemVssConnection: 'http://teamfoundation.environment.nsw.gov.au:8080/tfs/OEH/'
139.             2017-07-10T01:17:17.9376261Z ##[debug]ENDPOINT_AUTH_SystemVssConnection: '********'
140.             2017-07-10T01:17:17.9396263Z ##[debug]ENDPOINT_DATA_SystemVssConnection (empty)
141.             2017-07-10T01:17:17.9406264Z ##[debug]Entering Get-OMType.
142.             2017-07-10T01:17:17.9416265Z ##[debug] TypeName: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
143.             2017-07-10T01:17:17.9426266Z ##[debug] OMKind: 'WebApi'
144.             2017-07-10T01:17:17.9436267Z ##[debug] OMDirectory: ''
145.             2017-07-10T01:17:17.9446268Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6'
146.             2017-07-10T01:17:17.9466270Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
147.             2017-07-10T01:17:17.9476271Z ##[debug]The type was not loaded.
148.             2017-07-10T01:17:17.9606284Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.OAuth.WebApi.dll'
149.             2017-07-10T01:17:17.9666290Z ##[debug]Not found.
150.             2017-07-10T01:17:17.9686292Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.OAuth.dll'
151.             2017-07-10T01:17:17.9706294Z ##[debug]Not found.
152.             2017-07-10T01:17:17.9716295Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.WebApi.dll'
153.             2017-07-10T01:17:17.9736297Z ##[debug]Loading assembly: C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.WebApi.dll
154.             2017-07-10T01:17:17.9766300Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.OAuth.VssOAuthAccessTokenCredential'
155.             2017-07-10T01:17:17.9786302Z ##[debug]The type was not loaded.
156.             2017-07-10T01:17:17.9806304Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.VisualStudio.Services.dll'
157.             2017-07-10T01:17:17.9836307Z ##[debug]Not found.
158.             2017-07-10T01:17:17.9846308Z ##[debug]Leaving Get-OMType.
159.             2017-07-10T01:17:17.9866310Z ##[debug]Entering Get-OMType.
160.             2017-07-10T01:17:17.9876311Z ##[debug] TypeName: 'Microsoft.VisualStudio.Services.Client.VssOAuthCredential'
161.             2017-07-10T01:17:17.9886312Z ##[debug] OMKind: 'WebApi'
162.             2017-07-10T01:17:17.9896313Z ##[debug] OMDirectory: ''
163.             2017-07-10T01:17:17.9916315Z ##[debug] Require: 'True'
164.             2017-07-10T01:17:17.9926316Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6'
165.             2017-07-10T01:17:17.9936317Z ##[debug]Testing whether type can be loaded: 'Microsoft.VisualStudio.Services.Client.VssOAuthCredential'
166.             2017-07-10T01:17:17.9956319Z ##[debug]The type was loaded successfully.
167.             2017-07-10T01:17:17.9996323Z ##[debug]Leaving Get-OMType.
168.             2017-07-10T01:17:18.0026326Z ##[debug]Leaving Get-VssCredentials.
169.             2017-07-10T01:17:18.0036327Z ##[debug]Entering Get-OMType.
170.             2017-07-10T01:17:18.0056329Z ##[debug] TypeName: 'Microsoft.TeamFoundation.Build.WebApi.BuildHttpClient'
171.             2017-07-10T01:17:18.0066330Z ##[debug] OMKind: 'WebApi'
172.             2017-07-10T01:17:18.0086332Z ##[debug] OMDirectory: ''
173.             2017-07-10T01:17:18.0096333Z ##[debug] Require: 'True'
174.             2017-07-10T01:17:18.0126336Z ##[debug]Defaulted OM directory to: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6'
175.             2017-07-10T01:17:18.0136337Z ##[debug]Testing whether type can be loaded: 'Microsoft.TeamFoundation.Build.WebApi.BuildHttpClient'
176.             2017-07-10T01:17:18.0166340Z ##[debug]The type was not loaded.
177.             2017-07-10T01:17:18.0176341Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.TeamFoundation.Build.WebApi.WebApi.dll'
178.             2017-07-10T01:17:18.0186342Z ##[debug]Not found.
179.             2017-07-10T01:17:18.0536377Z ##[debug]Testing leaf path: 'C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.TeamFoundation.Build.WebApi.dll'
180.             2017-07-10T01:17:18.0546378Z ##[debug]Loading assembly: C:\PVV_agent\tasks\WorkItemUpdater\1.3.6\Microsoft.TeamFoundation.Build.WebApi.dll
181.             2017-07-10T01:17:18.0666390Z ##[debug]Testing whether type can be loaded: 'Microsoft.TeamFoundation.Build.WebApi.BuildHttpClient'
182.             2017-07-10T01:17:18.0676391Z ##[debug]The type was loaded successfully.
183.             2017-07-10T01:17:18.0686392Z ##[debug]Leaving Get-OMType.
184.             2017-07-10T01:17:18.0716395Z ##[debug]Constructing HTTP client.
185.             2017-07-10T01:17:18.0736397Z ##[debug]Leaving Get-VssHttpClient.
186.             2017-07-10T01:17:18.0746398Z ##[debug]GetBuildWorkItemsRefsAsync 34147a9c-0c69-4132-aa13-4e2cd697ac95 624
187.             2017-07-10T01:17:18.6406964Z ##[debug]Loop workItemsRefs
188.             2017-07-10T01:17:18.6767000Z ##[debug]Found WorkItemRef: 2009
189.             2017-07-10T01:17:18.8447168Z ##[debug]Found WorkItem: 2009
190.             2017-07-10T01:17:18.8467170Z ##[debug]Skipped Task WorkItem: 2009
191.             2017-07-10T01:17:18.8477171Z ##[debug]Found WorkItemRef: 1896
192.             2017-07-10T01:17:18.8987222Z ##[debug]Found WorkItem: 1896
193.             2017-07-10T01:17:18.8987222Z Updating WorkItem 1896
194.             2017-07-10T01:17:18.9027226Z ##[debug]Found KanbanColumn: WEF_13B56BE23846402A897F92E3C089F35C_Kanban.Column WEF_D0CEBEC070DA4D549967B81DF159CD86_Kanban.Column WEF_C54A9D74724A40879251DD62A6A5A4C4_Kanban.Column WEF_B9CFDA2C487E4819BFB2C149BBE69E55_Kanban.Column WEF_90C4902BB70E426796AB02912F3948E7_Kanban.Column WEF_FBFDA0C4023D47D9927933703E6E21DC_Kanban.Column WEF_CE3336052F9147E3A2A08F3D8493B002_Kanban.Column
195.             2017-07-10T01:17:18.9157239Z ##[debug]Patch: /fields/System.State Active
196.             2017-07-10T01:17:18.9417265Z ##[debug]Patch: /fields/WEF_13B56BE23846402A897F92E3C089F35C_Kanban.Column.Done False
197.             2017-07-10T01:17:18.9427266Z ##[debug]Patch: /fields/WEF_D0CEBEC070DA4D549967B81DF159CD86_Kanban.Column.Done False
198.             2017-07-10T01:17:18.9427266Z ##[debug]Patch: /fields/WEF_C54A9D74724A40879251DD62A6A5A4C4_Kanban.Column.Done False
199.             2017-07-10T01:17:18.9437267Z ##[debug]Patch: /fields/WEF_B9CFDA2C487E4819BFB2C149BBE69E55_Kanban.Column.Done False
200.             2017-07-10T01:17:18.9447268Z ##[debug]Patch: /fields/WEF_90C4902BB70E426796AB02912F3948E7_Kanban.Column.Done False
201.             2017-07-10T01:17:18.9457269Z ##[debug]Patch: /fields/WEF_FBFDA0C4023D47D9927933703E6E21DC_Kanban.Column.Done False
202.             2017-07-10T01:17:18.9467270Z ##[debug]Patch: /fields/WEF_CE3336052F9147E3A2A08F3D8493B002_Kanban.Column.Done False
203.             2017-07-10T01:17:19.3537677Z Process is terminated due to StackOverflowException.
204. 2017-07-10T01:17:19.9208244Z ##[error]Process completed with exit code 255.

**Comment by RelatedItemSearchUser** [comment]
That fixed my issue, Thanks!
