### ISSUE TITLE
Stackoverflow Exception

### ISSUE THREAD

**Issue by rol-dave-overall** [BlueBasher/WorkItemUpdater#14]
I have run into another variant of the StackOverFlow Exception as a result of the call to "UpdateWorkItemAsync". 

After doing some digging and debugging I managed to find that the problem was caused by you always setting the "Done" field of the Kanban column to either true/false based on the checkbox. I have the work item in an "In Progress" column and wanted it to automatically move into the next "Pull Request" column and neither of these are split columns. 

I suggest that you wrap the setting of the "Done" field with a check to see if the checkbox is true and only perform the change in this instance.

**Comment by BlueBasher** [comment]
Thanks for the investigation. I modified the code so it only updates kanban done fields if that field also actually exists in the workitem. A new version (1.4.716) has been deployed that should fix this.

**Comment by rol-dave-overall** [comment]
Updated to the new version and still getting an error, I am trying to move the item from the "In Progress" column to the "Pull Request" column

2017-11-30T11:36:29.5461196Z 
2017-11-30T11:36:29.5461196Z Process is terminated due to StackOverflowException.
2017-11-30T11:36:56.7811300Z ##[error]Exit code -1073741571 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'd:\a\_tasks\WorkItemUpdater_7164116a-ed17-48be-9c53-b440b2b1dd2e\1.4.716\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'Continue' ; $DebugPreference = 'Continue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''d:\a\_tasks\WorkItemUpdater_7164116a-ed17-48be-9c53-b440b2b1dd2e\1.4.716\task.ps1'''))"'.
